name: deploy multi-docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t abhisharma811/complex-fib -f ./client/Dockerfile.dev ./client
      - run: docker build -t abhisharma811/multi-client ./client
      - run: docker build -t abhisharma811/multi-nginx ./nginx
      - run: docker build -t abhisharma811/multi-server ./server
      - run: docker build -t abhisharma811/multi-worker ./worker

      - run: docker push abhisharma811/multi-client:latest
      - run: docker push abhisharma811/multi-nginx:latest
      - run: docker push abhisharma811/multi-server:latest
      - run: docker push abhisharma811/multi-worker:latest

      - name: run test cases
        run: |
          docker run -e CI=true abhisharma811/complex-fib npm test
